### ISSUE TITLE
No error code returned for missing user/password fields

### ISSUE THREAD

**Issue by katelynienaber** [zowe/zowe-cli-scs-plugin#27]
The SCS plugin is not compatible with profiles whose yaml file doesn't contain a user/password field.

When I try to use a profile with one of these fields missing, I get error:
_'Unable to store the secure field "user" associated with the profile "profName" of type "zosmf".'_

**The issue: This error message does not have an error code attached to it.**

In Zowe Explorer, since we allow optional credentials, we handle this error differently. We currently must check the error message string to see if it contains matching text.

This is problematic when using VSCode in other languages.

**Comment by awharn** [comment]
@katelynienaber Can you try deleting the z/OSMF meta yaml in your ~/.zowe/profiles/zosmf directory, running a `zowe profiles list zosmf` command, and trying again? There seems to be a problem where, if a profile structure is modified, Imperative does not update the profile meta.yaml, causing the SCS to believe the fields 'user' and 'password' are still required on the z/OSMF profile.

**Comment by tjohnsonBCM** [comment]
@katelynienaber What version of the SCS plugin do you have installed? There were issues related to storing optional fields that were fixed in v4.0.2. If your SCS version is newer than that, perhaps the problem is related to what @awharn mentioned.

**Comment by awharn** [comment]
I do agree that we should have an error code when it fails like this; we will look into adding that as we look into regenerating the meta.yaml

**Comment by katelynienaber** [comment]
@awharn I tried this trick and the error still came up. I'm asking some other people to try too...

@tjohnsonBCM my SCS version is 4.1.0

The function I'm calling is `CliProfileManager.save()`

And zosmf profile yaml looks like:
````
rejectUnauthorized: false
host: hostname.com
port: 1234
````

**Comment by zFernand0** [comment]
This enhancement has had no activity for 12 months. The issue also has less than 5 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
